# Generated by Django 5.0.6 on 2024-07-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='student_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
